### ISSUE TITLE
no libsigar-amd64-linux.so in java.library.path

### ISSUE THREAD

**Issue by karthika-ab** [rdkcentral/xconfserver#22]
We have observed the folllowing exception in both xconf-data-service and xconf-angular-admin during  mvn clean install 

```
[INFO] Running com.comcast.xconf.CompleteTestSuite
no libsigar-amd64-linux.so in java.library.path
org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
	at org.apache.cassandra.utils.SigarLibrary.<init>(SigarLibrary.java:47)
	at org.apache.cassandra.utils.SigarLibrary.<clinit>(SigarLibrary.java:28)
	at org.apache.cassandra.service.StartupChecks$7.execute(StartupChecks.java:216)
	at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:112)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:196)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)   
```

We were able to resolve the above exception  by  copying the .so file to the path /usr/lib

**Comment by gdj-cmcst** [comment]
As noted from examination:

A configuration needs to be set in the running system. As observed, the code itself is fine despite the error. Further investigation is needed to determine a proper fix.

**Comment by gstolz** [comment]
How can this be added on Windows? I tried to set as ENV and as systemPropertyVariables setting in surefire plugin. But non seems to be picked up.
Even though this lib seems to be platform-dependent (probably the reason why it's not inside Maven pom yet), I think it would be helpful to have versions for Linux/Windows included. Then build process would work out-of-the-box and a Github actions pipeline could be setup easily.

**Comment by gstolz** [comment]
seems like it is not so easy to integrate this with Maven...
Maybe[ this approach ](http://maven.40175.n5.nabble.com/How-to-tell-Maven-to-put-DLL-dependency-into-java-library-path-td5748568.html)would be an option:

- Use maven profile to detect OS arch and set it into a maven property

- Use maven-dependcy-plugin to down all requires dll.  Make sure to
take advantage of the property set in step 1

- Configure maven-surefire-plugin to set PATH env variable into the
download directory
